spring.application.name=HomeAcc
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
server.servlet.session.tracking-modes=cookie
server.port=8080

spring.thymeleaf.cache=false       
spring.freemarker.cache=false      
spring.web.resources.static-locations=file:./src/main/resources/static/
spring.web.resources.cache.period=0